services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phonebook-frontend-dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phonebook-backend-dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:1.20.1
    container_name: phonebook-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
